name: Terraform Deploy

on:
  push:
    branches:
      - main   # ya jis branch pe tum deploy karna chahte ho
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: Chomu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update apt and install dependencies
      run: sudo apt-get update -y

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: latest

    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
   
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    # 👇 Apply ko optional rakho ya approval ke saath use karo
    - name: Terraform Apply
      run: terraform apply -auto-approve
